[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.37"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000
fs_permissions = [{ access = "read", path = "./config" }]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 64
fail_on_revert = false

[rpc_endpoints]
robinhood_mainnet = "${ROBINHOOD_MAINNET}"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
sort_imports = true
